name: Recent Activity
on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:
permissions:
  contents: write
concurrency:
  group: update-profile-readme
  cancel-in-progress: true
jobs:
  update-readme:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Update recent activity
        uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
